import type { Comparison, Confusion } from "./types";

/** The guide's fifteen, verbatim in substance. */
export const CONFUSIONS: Confusion[] = [
  {
    id: "window-periods",
    number: 1,
    title: "Window is in periods, not minutes",
    body: "A 75-minute MA on 5-minute bars is window=15. Getting this wrong cascades through every later calculation.",
    sectionSlug: "bollinger-logic",
    source: "guide",
  },
  {
    id: "zero-indexed",
    number: 2,
    title: "Zero-indexed ranking",
    body: "4th-highest is .iloc[3]. The 6th split is split_5.",
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "two-dropna",
    number: 3,
    title: "Two dropna() calls are needed",
    body: "One with axis=1 for assets with missing prices, one with axis=0 for the NaN first row that pct_change() always creates.",
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "fee-decimal",
    number: 4,
    title: "0.1% = 0.001",
    body: "Not 0.01 and not 0.1. A monthly risk-free rate of 0.1% is 0.001.",
    sectionSlug: "formulas",
    source: "guide",
  },
  {
    id: "annual-to-monthly",
    number: 5,
    title: "Annual to monthly risk-free rate",
    body: "2% annual becomes 0.02/12.",
    sectionSlug: "formulas",
    source: "guide",
  },
  {
    id: "composition-property",
    number: 6,
    title: "composition is a property",
    body: "CALM.composition() raises TypeError. Properties never take parentheses.",
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "boolean-caps",
    number: 7,
    title: "Boolean literals are True / False",
    body: "Only the initial letter is capitalised. TRUE, FALSE, true and false are all invalid.",
    sectionSlug: "python-syntax",
    source: "guide",
  },
  {
    id: "interval-lowercase",
    number: 8,
    title: 'interval="1mo" must be lowercase',
    body: '"1mO" is an error.',
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "symbol-capital",
    number: 9,
    title: ".Symbol is capitalised",
    body: "In the ASSETS csv the column is Symbol. Attribute access is case sensitive.",
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "percent-before-round",
    number: 10,
    title: "Convert to a percentage before rounding",
    body: "Otherwise 0.0234 rounds to 0.02 instead of 2.34.",
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "tolist-alias",
    number: 11,
    title: ".tolist() and .to_list() are both valid",
    body: "They are aliases. Neither is an error.",
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "shape-counting",
    number: 12,
    title: "Shape counting: the index is not a column",
    body: "Date + 6 price columns gives shape (n, 6).",
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "head-default",
    number: 13,
    title: "head() returns 5 rows by default",
    body: "n is the first argument, so head(9) works without naming it.",
    sectionSlug: "code",
    source: "guide",
  },
  {
    id: "second-band-value",
    number: 14,
    title: '"Second band value" means second non-NaN value',
    body: "Use .dropna().iloc[1].",
    sectionSlug: "bollinger-logic",
    source: "guide",
  },
  {
    id: "numbers-differ",
    number: 15,
    title: "Your numbers may not match a key exactly",
    body: "Yahoo revises adjusted closes and the index csv is rebuilt monthly. Trust your own run.",
    sectionSlug: "code",
    source: "guide",
  },
];

/** The guide's eight tested distinctions. */
export const COMPARISONS: Comparison[] = [
  {
    id: "adjclose-close",
    a: "Adj Close",
    b: "Close",
    distinction:
      "Adj Close for returns (includes dividends and splits, gets revised over time). Close for strategies and Bollinger Bands.",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "axis",
    a: "axis=0",
    b: "axis=1",
    distinction:
      "0 drops rows (the default), 1 drops columns (used to drop assets with any NaN).",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "start-end",
    a: "start=",
    b: "end=",
    distinction: "start is inclusive, end is exclusive.",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "method-property",
    a: "Method",
    b: "Property",
    distinction: "A method takes (), a property never does.",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "function-method",
    a: "Function",
    b: "Method",
    distinction:
      "A function stands alone; a method is reached through the dot operator.",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "crossing-comparison",
    a: "crossed_below",
    b: "<",
    distinction: "Crossing is True only on the transition bar.",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "objective",
    a: "MINIMIZE_RISK",
    b: "MAXIMIZE_RATIO",
    distinction:
      "Min risk needs no risk-free rate; max Sharpe requires risk_free_rate=.",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "strategy-benchmark",
    a: "Strategy line",
    b: "Benchmark line",
    distinction: "The benchmark is passive buy-and-hold.",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "int-float",
    a: "int",
    b: "float",
    distinction: "Whole versus decimal.",
    sectionSlug: "comparisons",
    source: "guide",
  },
  {
    id: "install-import",
    a: "Installing",
    b: "Importing",
    distinction: "Installing is once; importing is required every session.",
    sectionSlug: "comparisons",
    source: "guide",
  },
];
